/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"

float *
add_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

    result = argp->n1 + argp->n2;
	return &result;
}

float *
sub_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

    result = argp->n1 - argp->n2;
	return &result;
}

float *
mul_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

    result = (argp->n1)*(argp->n2);
	return &result;
}

float *
div_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

    result = argp->n1/argp->n2;
	return &result;
}
