/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATE_H_RPCGEN
#define _CALCULATE_H_RPCGEN

#include <rpc/rpc.h>
#include <math.h>


#ifdef __cplusplus
extern "C" {
#endif


struct valid{
    int v;
    float n;
};
typedef struct valid valid;

struct oper{
    int v;
    char op;
};
typedef struct oper oper;

struct input {
	float n1;
	float n2;
};
typedef struct input input;

#define CALCULATE_PROG 0x31111111
#define CALCULATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  float * add_1(input *, CLIENT *);
extern  float * add_1_svc(input *, struct svc_req *);
#define SUB 2
extern  float * sub_1(input *, CLIENT *);
extern  float * sub_1_svc(input *, struct svc_req *);
#define MUL 3
extern  float * mul_1(input *, CLIENT *);
extern  float * mul_1_svc(input *, struct svc_req *);
#define DIV 4
extern  float * div_1(input *, CLIENT *);
extern  float * div_1_svc(input *, struct svc_req *);
extern int calculate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  float * add_1();
extern  float * add_1_svc();
#define SUB 2
extern  float * sub_1();
extern  float * sub_1_svc();
#define MUL 3
extern  float * mul_1();
extern  float * mul_1_svc();
#define DIV 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calculate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATE_H_RPCGEN */
